name: Python GKE deploy pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install python libraries
        run: pip install pyyaml

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/422876046186/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-sa@terraform2-demoqr8.iam.gserviceaccount.com"

      - name: Connect to GKE cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "datametica-gke-cluster"
          location: "asia-south1"

      - name: Pun python Gitops script
        run: python3 yaml_parser.py
